;; C
(load "~/.emacs.d/languages/c.el")
;; Markdown
(load "~/.emacs.d/languages/markdown.el")
;; Ruby
(load "~/.emacs.d/languages/ruby.el")
;; LaTeX
(load "~/.emacs.d/languages/latex.el")
;; Haskell
(load "~/.emacs.d/languages/haskell.el")
;; Scala
(load "~/.emacs.d/languages/scala.el")
;; Org-mode
(load "~/.emacs.d/languages/org.el")
;; Ocaml
(load "~/.emacs.d/languages/ocaml.el")
;; Python
(load "~/.emacs.d/languages/python.el")
;; Groovy (Gradle)
(load "~/.emacs.d/languages/groovy.el")
;; Scheme
;(load "~/.emacs.d/languages/scheme.el")
;; Golang
(load "~/.emacs.d/languages/golang.el")
